@Library('olympus') _
showtime.apiKey = "6d2c7f9da9b0526209ff798a2386b776121beea98c01fca21d1a0b17ee791575"
olympus.namespace = "hedgehog"
olympus.dockerImage = "docker.dc.xing.com/hedgehog/profile-finder-ui"
olympus.sourceRepository = "https://source.xing.com/hedgehog/profile-finder-ui.git"
olympus.productionBranch = 'master'
olympus.previewBranch = 'develop'

olympusDefaultPipeline(
    this,
    compileAndTestCmd: {
        def sbt = "${tool name: 'sbt-0.13.13', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder$SbtInstallation'}/bin/sbt -no-colors"
        sh "$sbt clean compile"
    },
    imageBuildCmd: { image, tag ->
        def sha1 = env.GIT_COMMIT
        sh "docker build --build-arg GIT_SHA1=${sha1} -t ${image}:${tag} ."
    }
)
